/*
 * MATLAB Compiler: 3.0
 * Date: Sun Jun 14 04:54:04 2009
 * Arguments: "-B" "macro_default" "-O" "all" "-O" "fold_scalar_mxarrays:on"
 * "-O" "fold_non_scalar_mxarrays:on" "-O" "optimize_integer_for_loops:on" "-O"
 * "array_indexing:on" "-O" "optimize_conditionals:on" "-M" "-silentsetup" "-d"
 * "C:/MATLAB6p5/work/mydatafit/src" "-B" "csglcom:mydatafit,mydatafit,1.0"
 * "-B" "sgl" "-m" "-W" "main" "-L" "C" "-t" "-T" "link:exe" "-h"
 * "libmmfile.mlib" "-W" "mainhg" "libmwsglm.mlib" "-t" "-W"
 * "comhg:mydatafit,mydatafit,1.0" "-T" "link:lib" "-h" "libmmfile.mlib" "-i"
 * "-i" "C:/MATLAB6p5/work/conv2num.m" "C:/MATLAB6p5/work/conv2str.m"
 * "C:/MATLAB6p5/work/mypolyfit.m" 
 */

#ifndef MLF_V2
#define MLF_V2 1
#endif

#include "libmatlb.h"
#include "mydatafit.h"
#include "conv2num.h"
#include "conv2str.h"
#include "mypolyfit.h"
#include "libmmfile.h"

extern _mex_information _lib_info;

static mexFunctionTableEntry function_table[3]
  = { { "conv2num", mlxConv2num, 1, 1, &_local_function_table_conv2num },
      { "conv2str", mlxConv2str, 1, 2, &_local_function_table_conv2str },
      { "mypolyfit", mlxMypolyfit, 3, 1, &_local_function_table_mypolyfit } };

static _mexInitTermTableEntry init_term_table[4]
  = { { libmmfileInitialize, libmmfileTerminate },
      { InitializeModule_conv2num, TerminateModule_conv2num },
      { InitializeModule_conv2str, TerminateModule_conv2str },
      { InitializeModule_mypolyfit, TerminateModule_mypolyfit } };

static int _reference_count = 0;

_mex_information _lib_info
  = { 1, 3, function_table, 0, NULL, 0, NULL, 4, init_term_table };

/*
 * The function "mydatafitInitialize" is a Compiler-generated initialization
 * wrapper. It is used to initialize the state of Compiler-generated functions
 * so that those functions can be called from code not generated by the
 * Compiler. The function(s) initialized can be found in the function_table
 * variable, appearing above.
 */
void mydatafitInitialize(void) {
    mclLibhgInit("mydatafit", &_reference_count, &_lib_info);
}

/*
 * The function "mydatafitTerminate" is a Compiler-generated termination
 * wrapper. It is used to clean up the state that was set up by the
 * initialization wrapper function, also found in this file. Call this function
 * after having called the initialization wrapper function and after having
 * finished making all calls to the Compiler-generated function(s) found in the
 * function_table variable, appearing above.
 */
void mydatafitTerminate(void) {
    mclLibhgTerm("mydatafit", &_reference_count, &_lib_info);
}
