/*
 * MATLAB Compiler: 3.0
 * Date: Sun Jun 14 18:30:54 2009
 * Arguments: "-B" "macro_default" "-O" "all" "-O" "fold_scalar_mxarrays:on"
 * "-O" "fold_non_scalar_mxarrays:on" "-O" "optimize_integer_for_loops:on" "-O"
 * "array_indexing:on" "-O" "optimize_conditionals:on" "-M" "-silentsetup" "-d"
 * "C:/MATLAB6p5/work/mywav/src" "-B" "csglcom:mywav,mywav,1.0" "-B" "sgl" "-m"
 * "-W" "main" "-L" "C" "-t" "-T" "link:exe" "-h" "libmmfile.mlib" "-W"
 * "mainhg" "libmwsglm.mlib" "-t" "-W" "comhg:mywav,mywav,1.0" "-T" "link:lib"
 * "-h" "libmmfile.mlib" "-i" "-i" "C:/MATLAB6p5/work/fzone.m"
 * "C:/MATLAB6p5/work/myprowav.m" "C:/MATLAB6p5/work/tzone.m" 
 */

#ifndef MLF_V2
#define MLF_V2 1
#endif

#include "libmatlb.h"
#include "mywav.h"
#include "fzone.h"
#include "myprowav.h"
#include "tzone.h"
#include "wavread.h"
#include "awgn.h"
#include "wavwrite.h"
#include "wgn.h"
#include "libmmfile.h"

extern _mex_information _lib_info;

static mexFunctionTableEntry function_table[7]
  = { { "fzone", mlxFzone, 1, 1, &_local_function_table_fzone },
      { "myprowav", mlxMyprowav, 4, 1, &_local_function_table_myprowav },
      { "tzone", mlxTzone, 1, 1, &_local_function_table_tzone },
      { "wavread", mlxWavread, 2, 4, &_local_function_table_wavread },
      { "awgn", mlxAwgn, -1, 1, &_local_function_table_awgn },
      { "wavwrite", mlxWavwrite, 4, 0, &_local_function_table_wavwrite },
      { "wgn", mlxWgn, -1, 1, &_local_function_table_wgn } };

static _mexInitTermTableEntry init_term_table[8]
  = { { libmmfileInitialize, libmmfileTerminate },
      { InitializeModule_fzone, TerminateModule_fzone },
      { InitializeModule_myprowav, TerminateModule_myprowav },
      { InitializeModule_tzone, TerminateModule_tzone },
      { InitializeModule_wavread, TerminateModule_wavread },
      { InitializeModule_awgn, TerminateModule_awgn },
      { InitializeModule_wavwrite, TerminateModule_wavwrite },
      { InitializeModule_wgn, TerminateModule_wgn } };

static int _reference_count = 0;

_mex_information _lib_info
  = { 1, 7, function_table, 0, NULL, 0, NULL, 8, init_term_table };

/*
 * The function "mywavInitialize" is a Compiler-generated initialization
 * wrapper. It is used to initialize the state of Compiler-generated functions
 * so that those functions can be called from code not generated by the
 * Compiler. The function(s) initialized can be found in the function_table
 * variable, appearing above.
 */
void mywavInitialize(void) {
    mclLibhgInit("mywav", &_reference_count, &_lib_info);
}

/*
 * The function "mywavTerminate" is a Compiler-generated termination wrapper.
 * It is used to clean up the state that was set up by the initialization
 * wrapper function, also found in this file. Call this function after having
 * called the initialization wrapper function and after having finished making
 * all calls to the Compiler-generated function(s) found in the function_table
 * variable, appearing above.
 */
void mywavTerminate(void) {
    mclLibhgTerm("mywav", &_reference_count, &_lib_info);
}
