/*
 * MATLAB Compiler: 3.0
 * Date: Sat Jun 13 16:15:23 2009
 * Arguments: "-B" "macro_default" "-O" "all" "-O" "fold_scalar_mxarrays:on"
 * "-O" "fold_non_scalar_mxarrays:on" "-O" "optimize_integer_for_loops:on" "-O"
 * "array_indexing:on" "-O" "optimize_conditionals:on" "-M" "-silentsetup" "-d"
 * "C:/MATLAB6p5/work/mymatrix/src" "-B" "ccom:mymatrix,mymatrix,1.0" "-t" "-W"
 * "com:mymatrix,mymatrix,1.0" "-T" "link:lib" "-h" "libmmfile.mlib" "-i" "-i"
 * "C:/MATLAB6p5/work/conv2fraction.m" "C:/MATLAB6p5/work/conv2num.m"
 * "C:/MATLAB6p5/work/conv2str.m" "C:/MATLAB6p5/work/GuassSeidel.m"
 * "C:/MATLAB6p5/work/myeye.m" "C:/MATLAB6p5/work/mymagic.m"
 * "C:/MATLAB6p5/work/myminus.m" "C:/MATLAB6p5/work/mymultiply.m"
 * "C:/MATLAB6p5/work/mypascal.m" "C:/MATLAB6p5/work/myplus.m"
 * "C:/MATLAB6p5/work/myrot.m" "C:/MATLAB6p5/work/mysolve.m" 
 */

#ifndef MLF_V2
#define MLF_V2 1
#endif

#include "libmatlb.h"
#include "mymatrix.h"
#include "conv2fraction.h"
#include "conv2num.h"
#include "conv2str.h"
#include "guassseidel.h"
#include "myeye.h"
#include "mymagic.h"
#include "myminus.h"
#include "mymultiply.h"
#include "mypascal.h"
#include "myplus.h"
#include "myrot.h"
#include "mysolve.h"
#include "libmmfile.h"

extern _mex_information _lib_info;

static mexFunctionTableEntry function_table[12]
  = { { "conv2fraction", mlxConv2fraction, 1, 1,
        &_local_function_table_conv2fraction },
      { "conv2num", mlxConv2num, 1, 1, &_local_function_table_conv2num },
      { "conv2str", mlxConv2str, 1, 2, &_local_function_table_conv2str },
      { "guassseidel", mlxGuassseidel, 3, 2,
        &_local_function_table_guassseidel },
      { "myeye", mlxMyeye, 1, 1, &_local_function_table_myeye },
      { "mymagic", mlxMymagic, 1, 1, &_local_function_table_mymagic },
      { "myminus", mlxMyminus, 2, 1, &_local_function_table_myminus },
      { "mymultiply", mlxMymultiply, 2, 1, &_local_function_table_mymultiply },
      { "mypascal", mlxMypascal, 1, 1, &_local_function_table_mypascal },
      { "myplus", mlxMyplus, 2, 1, &_local_function_table_myplus },
      { "myrot", mlxMyrot, 1, 1, &_local_function_table_myrot },
      { "mysolve", mlxMysolve, 2, 1, &_local_function_table_mysolve } };

static _mexInitTermTableEntry init_term_table[13]
  = { { libmmfileInitialize, libmmfileTerminate },
      { InitializeModule_conv2fraction, TerminateModule_conv2fraction },
      { InitializeModule_conv2num, TerminateModule_conv2num },
      { InitializeModule_conv2str, TerminateModule_conv2str },
      { InitializeModule_guassseidel, TerminateModule_guassseidel },
      { InitializeModule_myeye, TerminateModule_myeye },
      { InitializeModule_mymagic, TerminateModule_mymagic },
      { InitializeModule_myminus, TerminateModule_myminus },
      { InitializeModule_mymultiply, TerminateModule_mymultiply },
      { InitializeModule_mypascal, TerminateModule_mypascal },
      { InitializeModule_myplus, TerminateModule_myplus },
      { InitializeModule_myrot, TerminateModule_myrot },
      { InitializeModule_mysolve, TerminateModule_mysolve } };

static int _reference_count = 0;

_mex_information _lib_info
  = { 1, 12, function_table, 0, NULL, 0, NULL, 13, init_term_table };

/*
 * The function "mymatrixInitialize" is a Compiler-generated initialization
 * wrapper. It is used to initialize the state of Compiler-generated functions
 * so that those functions can be called from code not generated by the
 * Compiler. The function(s) initialized can be found in the function_table
 * variable, appearing above.
 */
void mymatrixInitialize(void) {
    mclLibInit("mymatrix", &_reference_count, &_lib_info);
}

/*
 * The function "mymatrixTerminate" is a Compiler-generated termination
 * wrapper. It is used to clean up the state that was set up by the
 * initialization wrapper function, also found in this file. Call this function
 * after having called the initialization wrapper function and after having
 * finished making all calls to the Compiler-generated function(s) found in the
 * function_table variable, appearing above.
 */
void mymatrixTerminate(void) {
    mclLibTerm("mymatrix", &_reference_count, &_lib_info);
}
